---
# Defines tasks applicable for postgreSQL

- name: Install official repo gpg key
  sudo: yes
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: ACCC4CF8
    state: present

- name: Install official repository
  sudo: yes
  apt_repository:
    repo: "deb https://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main"
    state: present
    update_cache: yes

# NOTE Using Debian's packages kept failing in the weirdest ways, hence a switch to upstream, hence the above tasks.

- name: Install Postgres
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql
    - python-psycopg2
    - libpq-dev
  tags:
    - dependencies

- name: Set password for PostgreSQL admin user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_admin_username }} password={{ db_admin_password }} encrypted=yes
